### PR TITLE
PR: Custom "initials" sorting and nested entries, formatting classes replaced by function

### PR DESCRIPTION
**Pull request by epsilonhalbe**
Hi,

first of all thanks for providing in-dexter.
I stumbled upon it and had the need for nested entries, e.g.

```
Sample
  blood              4
  tissue              5
```

I also found that Symbols, like `(+)` would get put into the index by `(` which is weird.

When implementing it I found the marker classes cumbersome, so I replaced that with functions which makes it a bit more powerful.

So I ended up replacing almost all of in-dexter and re-write it.

My first question - is this still something that you want to maintain or are those changes too big, then I will fork this package and give it a new name.

I have not updated the docs (yet) - but I wanted to give you a heads up.

How much do you value backwards compatibility? - should I include a "index-main" function? or are you happy to break stuff.

All the best
Martin

### CODE REVIEW

**Comment by RolfBremer** [comment]
Hi Martin,

I really like what you did - especially the nesting and formatting functionality.
I will test the changes against our document base during the next days and would like to include it into in-dexter, if that is OK for you.

best regards

Rolf

**Comment by RolfBremer** [comment]
Regarding the index-main() function: I still like the idea to abstract the semantic, or at least having the format definition in one place. Of course Typst allows it easily to define index-xxx() at any time, so it can just be defined on ones needs. Maybe we should include an index-main() to show how it is done and reduce the breaking changes a bit?
What do you think?

All the best

Rolf

**Comment by epsilonhalbe** [comment]
image
this is the index now in the sample-usage.pdf

**Comment by RolfBremer** [comment]
Great! 
I agree, the as-text method is a bad hack we had to use to work with the content type. I still hope to have a build-in method to retrieve text from content some day. 

Regarding the "index-main": I like to have the markup methods separated from the formatting.  So instead of "index-bold", which specifies an appearance, let us express the semantic of the index entry, like in "index-main". This way, the appearance of a text can be changed without changing the markup of the content.

I think this leads to having index-main defined as 

```typ
#let index-main = index.with(fmt:strong) 
```

as a default. This can easily changed by the user to accommodate his or her design needs.

**Comment by epsilonhalbe** [comment]
fair point, I'll fix that last bit tomorrow

**Comment by epsilonhalbe** [comment]
DONE - wooo

**Comment by epsilonhalbe** [comment]
Please have a look at the pdf document and the readme if I missed something.

**Comment by RolfBremer** [comment]
OK, my documents are running fine with the new package - even without breaking changes.
We will merge them today and after some more tests, submit them to the typst packages repo.
Thanks again for the nice work!

Rolf

**Pull request merged**
